# Site Variables --------------------------------------------------------------

title: Cozyring

# Jekyll Config ---------------------------------------------------------------

collections:
  ring:
    output: true
    permalink: /embed/:title

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_ring"
    values:
      layout: embed

exclude:
  - serve.sh
